GET http://127.0.0.1:6969/categoria

### 
GET http://127.0.0.1:6969/categoria/1

### 
DELETE http://127.0.0.1:6969/categoria/2

### 
GET http://127.0.0.1:6969/categoria/3

### 
GET http://127.0.0.1:6969/categoria?title=Graficas 

### 
GET http://127.0.0.1:6969/categoria?title=Procesadores 

### 
GET http://127.0.0.1:6969/categoria?multitle=Procesadores,Graficas 

###
POST http://127.0.0.1:6969/categoria 
Content-Type: application/json
{
    "id" :1, 
    "title" : "Graficas"
}

### 
PUT http://127.0.0.1:6969/categoria
Content-Type: application/json
{
    "id": 2, 
    "title" : "Procesador"
}