GET http://127.0.0.1:6969/Categoria

### 
GET http://127.0.0.1:6969/Categoria/1

### 
DELETE http://127.0.0.1:6969/Categoria/2

### 
GET http://127.0.0.1:6969/Categoria/3

### 
GET http://127.0.0.1:6969/Categoria?title=Graficas 

### 
GET http://127.0.0.1:6969/Categoria?title=Procesadores 

### 
GET http://127.0.0.1:6969/Categoria?multitle=Procesadores,Graficas 

###
POST http://127.0.0.1:6969/Categoria Content-Type: application/json

{
    "id" :1, 
    "title" : "Graficas"
}

### 
PUT http://127.0.0.1:6969/Categoria

Content-Type: application/json
{
    "id": 2, 
    "title" : "Procesador"
}