GET http://127.0.0.1:6969/Marca

### 
GET http://127.0.0.1:6969/Marca/1

### 
DELETE http://127.0.0.1:6969/Marca/2

### 
GET http://127.0.0.1:6969/Marca/3

### 
GET http://127.0.0.1:6969/Marca?title=GTX 

### 
GET http://127.0.0.1:6969/Marca?title=AMD 

### 
GET http://127.0.0.1:6969/Marca?multitle=ASUS,IntelCore 

###
POST http://127.0.0.1:6969/Marca 
Content-Type: application/json

{
    "id" :10, 
    "title" : "Palit"
}

### 
PUT http://127.0.0.1:6969/Marca
Content-Type: application/json

{
    "id": 25, 
    "title" : "FullCollor"
}