### 
GET http://localhost:6969/MedioDePago/

### 
GET http://localhost:6969/MedioDePago/1

### 
DELETE http://localhost:6969/MedioDePago/3

### 
GET http://localhost:6969/MedioDePago/2

### 
GET http://localhost:6969/MedioDePago?title=Debito

### 
GET http://localhost:6969/MedioDePago?multitle=Credito,Efectivo

### 
POST http://127.0.0.1:6969/MedioDePago 
Content-Type: application/json

{
"id": 5, "title" : "Tranferencia"
}