###
POST http://127.0.0.1:6969/objeto
Content-Type: application/json
Authorization: Bearer {{ login.response.body.token }}

{
  "title" : "Nuestra API",
  "content" : "La mejor api que hayas visto en tu vida"
}