GET http://127.0.0.1:6969/Productos

### 
GET http://127.0.0.1:6969/Productos/1

### 
GET http://127.0.0.1:6969/Productos/4

### 
GET http://127.0.0.1:6969/Productos?nombre=AMD

### 
GET http://127.0.0.1:6969/Productos?precio=15109

### 
GET http://127.0.0.1:6969/Productos?descripcion=gama

### 
GET http://127.0.0.1:6969/Productos?descripcion=exelente&categoria=Graficas

### 
GET http://127.0.0.1:6969/Productos?multitle=AMD,GTX

### 
GET http://127.0.0.1:6969/Productos?search=ASUS

### 
GET http://127.0.0.1:6969/Productos/categoria?categoria=Mother

### 
GET http://127.0.0.1:6969/Productos/destacados

### 
GET http://127.0.0.1:6969/Productos/marca?marca=ASUS

### 
GET http://127.0.0.1:6969/Productos/az
