GET http://127.0.0.1:6969/Productos

### 
GET http://127.0.0.1:6969/Productos/1

### 
DELETE http://127.0.0.1:6969/Productos/3

### 
GET http://127.0.0.1:6969/Productos/4

### 
GET http://127.0.0.1:6969/Productos?nombre=AMD

### 
GET http://127.0.0.1:6969/Productos?precio=15109

### 
GET http://127.0.0.1:6969/Productos?descripcion=gama

### 
GET  http://127.0.0.1:6969/Productos/categoria?categoria=Mother


### 
GET http://127.0.0.1:6969/Productos?search=ASUS

### 
GET http://127.0.0.1:6969/Productos/destacados

### 
GET http://127.0.0.1:6969/Productos/marca?marca=ASUS

### 
POST http://127.0.0.1:6969/Productos/1

Content-Type: application/json Authorization: Bearer {{ login.response.body.token }}

{
"nombre": "AMD RX 6600 8GB DDR6", 
"precio": 14719, 
"activo": true, 
"descripcion": "nos pones un 10?",
"marca":"AMD",
"categoria":"grafica"
}

### 
PUT http://127.0.0.1:6969/Productos/2
Content-Type: application/json Authorization: Bearer {{ login.response.body.token }}

{
"nombre":"VIDEO GEFORCE GTX 1650 4GB EVGA SC ULTRA",
"precio":15109,
"activo":true,
"descripcion":"exelente para un gamer promedio",
"categoria":"grafica",
"marca":"GTX"
}