# @name login 
POST http://127.0.0.1:6969/login Content-Type: application/json

{
    "username":"admin", 
    "password":"123456"
}

### 
POST http://127.0.0.1:6969/Users Content-Type: application/json
Authorization: Bearer{{ login.response.body.token }}

{ 
    "id": 1,
    "nombre": "Alan",
    "apellido": "Gimelstein",
    "mail": "alan@gmail.com", 
    "pass": ""
}

### 
GET http://127.0.0.1:6969/Users

### 
DELETE http://127.0.0.1:6969/Users/2

### 
GET http://127.0.0.1:6969/Users/3

### 
GET http://127.0.0.1:6969/Users?nombre=Alan
### 
GET http://127.0.0.1:6969/Users?apellido=Gimelstein
### 
GET http://127.0.0.1:6969/Users?nombre=Gonzalo&apellido=Garcia

### 
GET http://127.0.0.1:6969/Users

### 
GET http://127.0.0.1:6969/Users?multinombres=Agustin,Alan

### 
GET http://127.0.0.1:6969/Users?buscar=Matias

### 
GET http://127.0.0.1:6969/Users?BuscadorMulti=Matias,Alan
