# @name login 
POST http://127.0.0.1:6969/login 
Content-Type: application/json

{
    "username":"admin", 
    "password":"123456"
}

### 
POST http://127.0.0.1:6969/usuarios 
Content-Type: application/json Authorization: Bearer {{ login.response.body.token }}

{ 
    "id": 1,
    "nombre": "Alan",
    "apellido": "Gimelstein",
    "mail": "alan@gmail.com", 
    " contrasenia": ""
}
/*
### 
POST http://127.0.0.1:6969/usuarios 
Content-Type: application/json

{
    "id": 4, "nombre": "Flavio", "apellido": "Profe", "mail": "Flavio@ingsis.com", "contrasenia": ""
}

### 
PUT http://127.0.0.1:6969/usuarios 
Content-Type: application/json

{
    "id": 2, "nombre": "Flavio", "apellido": "Profe", "mail": "Flavio@ingsis.com", "contrasenia": ""
}
*/
### 
GET http://127.0.0.1:6969/usuarios

### 
DELETE http://127.0.0.1:6969/usuarios/2

### 
GET http://127.0.0.1:6969/usuarios/3

### 
GET http://127.0.0.1:6969/usuarios?nombre=Alan
### 
GET http://127.0.0.1:6969/usuarios?apellido=Gimelstein
### 
GET http://127.0.0.1:6969/usuarios?nombre=Gonzalo&apellido=Garcia

### 
GET http://127.0.0.1:6969/usuarios

### 
GET http://127.0.0.1:6969/usuarios?multinombres=Agustin

### 
GET http://127.0.0.1:6969/usuarios?buscar=Matias

### 
GET http://127.0.0.1:6969/usuarios?BuscadorMulti=Matias,Alan

### 
GET http://127.0.0.1:6969/usuario?multisearch=Gonzalo,Matias